@{
    AppId             = 'com.letsgoup.uservego.staging'
    IosAppId          = 'com.letsgoup.uServeGo.staging'
    StoreEmail        = 'chunweili+william-stg-store-001@letsgoup.tw'
    StorePassword     = 'Qaz1234567'
    StoreOwner        = 'william-stg-store-contact-001'
    StoreOwnerPin     = '1940'
    StaffA            = 'william-stg-staff-001'
    StaffAEmail       = 'chunweili+william-stg-staff-001@letsgoup.tw'
    StaffAPhone       = '9189359819'
    StaffAPassword    = 'Qaz1234567'
    StaffAPin         = '5660'
    UserRolePhone     = '9189359819'
    UserRoleEmail     = 'chunweili+william-stg-staff-001@letsgoup.tw'
    UserRolePassword  = 'Qaz1234567'
    OwnerRolePhone    = '9189359820'
    OwnerRolePassword = 'Qaz1234567'
    AdminRoleName     = 'william-stg-staff-004'
    AdminRoleEmail    = 'chunweili+william-stg-staff-004@letsgoup.tw'
    AdminRolePhone    = '1111111133'
    AdminRolePassword = 'Qaz1234567'
    AdminRolePin      = '2407'
    StaffB            = 'william-stg-staff-002'
    StaffBEmail       = 'chunweili+william-stg-staff-002@letsgoup.tw'
    StaffBPin         = '2878'
    InactiveStaff     = 'william-stg-staff-003'
    InactiveStaffEmail = 'chunweili+william-stg-staff-003@letsgoup.tw'
    InactiveStaffPin  = '3102'
    InvalidPin        = '0000'
    StaffAMarker      = 'william-stg-staff-001'
    StaffBMarker      = 'william-stg-staff-002'
    StoreMarker       = 'william-stg-store-001'

    # Merchant-level fixtures for the Switch Store suite.
    MerchantName      = 'william-stg-merchant-003'
    MerchantEmail     = 'chunweili+william-stg-merchant-003@letsgoup.tw'
    MerchantPassword  = 'Qaz1234567'
    MerchantPin       = '3197'
    SwitchStoreA      = 'william-stg-store-006'
    SwitchStoreAEmail = 'chunweili+william-stg-store-006@letsgoup.tw'
    SwitchStoreAPin   = '3626'
    SwitchStoreB      = 'william-stg-store-007'
    InactiveStore     = 'william-stg-store-008'
    InactiveStoreEmail = 'chunweili+william-stg-store-008@letsgoup.tw'
    InactiveStorePassword = 'Qaz1234567'
    InactiveStorePin  = '6137'
}
