@{
    AppId             = 'com.letsgoup.uservego.staging'
    StoreEmail        = 'chunweili+william-stg-store-001@letsgoup.tw'
    StorePassword     = 'Qaz1234567'
    StoreOwner        = 'william-stg-store-contact-001'
    StoreOwnerPin     = '1940'
    StaffA            = 'william-stg-staff-001'
    StaffAEmail       = 'chunweili+william-stg-staff-001@letsgoup.tw'
    StaffAPin         = '5660'
    StaffB            = 'william-stg-staff-002'
    StaffBEmail       = 'chunweili+william-stg-staff-002@letsgoup.tw'
    StaffBPin         = '2878'
    InactiveStaff     = 'william-stg-staff-003'
    InactiveStaffEmail = 'chunweili+william-stg-staff-003@letsgoup.tw'
    InactiveStaffPin  = '3102'
    InvalidPin        = '0000'
    StaffAMarker      = 'william-stg-staff-001'
    StaffBMarker      = 'william-stg-staff-002'
    StoreMarker       = 'william-stg-store-001'
}
